WS4813/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace WSBangHang_4813.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required, StringLength(50)]
        public string Name { get; set; }
        public List<Product>? Products { get; set; }
    }
}

WS4813/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WSBangHang_4813.Models;
using WSBangHang_4813.Repositories;

namespace WSBangHang_4813.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        // Hiển thị danh sách danh mục
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryRepository.GetAllAsync();
            return View(categories);
        }

        // Hiển thị form thêm danh mục mới
        public IActionResult Add()
        {
            return View();
        }

        // Xử lý thêm danh mục mới
        [HttpPost]
        public async Task<IActionResult> Add(Category category)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.AddAsync(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // Hiển thị thông tin chi tiết danh mục
        public async Task<IActionResult> Display(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // Hiển thị form cập nhật danh mục
        public async Task<IActionResult> Update(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // Xử lý cập nhật danh mục
        [HttpPost]
        public async Task<IActionResult> Update(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _categoryRepository.UpdateAsync(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // Hiển thị form xác nhận xóa danh mục
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // Xử lý xóa danh mục
        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _categoryRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WS4813/Views/Category/Add.cshtml
@model WSBangHang_4813.Models.Category
<head>
    <link href="~/css/add.css" rel="stylesheet" />
</head>
<h2>Add Category</h2>

<form method="post" action="@Url.Action("Add", "Category")">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" id="name" name="Name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Thêm</button>
</form>

WS4813/Views/Category/Delete.cshtml
@model WSBangHang_4813.Models.Category
<
<head>
    <link href="~/css/addcte.css" rel="stylesheet" />
</head>

<h2>Xác nhận xóa danh mục</h2>

<p>Bạn có chắc chắn muốn xóa danh mục này không?</p>

<form method="post" action="@Url.Action("DeleteConfirmed", "Category", new { id = Model.Id })">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="form-group">
        <label for="name">Tên danh mục:</label>
        <input type="text" id="name" name="Name" value="@Model.Name" class="form-control" readonly />
    </div>
    <button type="submit" class="btn btn-danger">Xóa</button>
    <a asp-action="Index" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
</form>

WS4813/Views/Category/Index.cshtml
@model IEnumerable<WSBangHang_4813.Models.Category>
<head>
    <link href="~/css/addcte.css" rel="stylesheet" />
</head>
<h2>Danh sách danh mục</h2>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td>@category.Id</td>
                <td>@category.Name</td>
                <td>
                    <a class="conten" href="@Url.Action("Update", "Category", new { id = category.Id })">Sửa</a> |
                    <a class="conten" href="@Url.Action("Delete", "Category", new { id = category.Id })">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
    <a class="conten" href="@Url.Action("Add", "Category")">Thêm danh mục mới</a>
</table>

WS4813/Views/Category/Update.cshtml
@model WSBangHang_4813.Models.Category
<head>
    <link href="~/css/add.css" rel="stylesheet" />
</head>
<h2>Cập nhật danh mục</h2>

<form method="post" action="@Url.Action("Update", "Category", new { id = Model.Id })">
    <div class="form-group">
        <label for="name">Tên danh mục:</label>
        <input type="text" id="name" name="Name" value="@Model.Name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Cập nhật</button>
    <a asp-action="Index" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
</form>